### PR TITLE
fix(cache): fix get external secret panic

### LINKED ISSUE #96: Fail to get external redis password secret

### PR DESCRIPTION
**Pull request by Ghostbaby**
fix get external secret panic

Fixes #96

Signed-off-by: zhuhuijun <zhuhuijunzhj@gmail.com>

### CODE REVIEW

File: controllers/cache/redis.go [hunk 1]
```diff
@@ -37,29 +37,33 @@ func (redis *RedisReconciler) Reconcile() (*lcm.CRStatus, error) {
...
+		crStatus, err := redis.Update(nil)
+		if err != nil {
+			return crStatus, err
+		}
 	}
 
-	crStatus, err = redis.Update(nil)
+	crStatus, err := redis.Readiness()
 	if err != nil {
 		return crStatus, err
```
Comment (wangcanfengxs) [inline controllers/cache/redis.go:68]: Like
```
	crStatus, err := postgres.Readiness()
	if err != nil {		
		return databaseNotReadyStatus(CheckDatabaseHealthError, err.Error()), err
	}
```

```suggestion
	crStatus, err := redis.Readiness()
	if err != nil {		
		return cacheNotReadyStatus(CheckCacheHealthError, err.Error()), err
	}
```
