### PR TITLE
fix(notary) fix the problem that Notary is unavailable

### LINKED ISSUE #143: Optional component `Notary` cannot be started
Probably because the data in the database secret is not correct

### PR DESCRIPTION
**Pull request by Ghostbaby**
Fix the problem that Notary is unavailable, and the optional component uses the database separately.

Fixes #143

Signed-off-by: zhuhuijun <zhuhuijunzhj@gmail.com>

### CODE REVIEW

File: controllers/database/generate.go [hunk 1]
```diff
@@ -78,9 +81,8 @@ func (postgres *PostgreSQLReconciler) generatePostgresCR() (*unstructured.Unstru
 }
 
 //generateHarborDatabaseSecret returns database connection secret
-func (postgres *PostgreSQLReconciler) generateHarborDatabaseSecret(conn *Connect, secretName string) *corev1.Secret {
-
-	return &corev1.Secret{
+func (postgres *PostgreSQLReconciler) generateHarborDatabaseSecret(conn *Connect, secretName, propertyName string) *corev1.Secret {
```
Comment (soulseen) [inline controllers/database/generate.go:84]: if I want to generate Clair Secret, can I write the logic in this function?

Comment (Ghostbaby) [reply controllers/database/generate.go:84]: yes

**Comment by wangcanfengxs** [comment]
LGTM
