### PR TITLE
fix(reconcile) add reconcile wait requeue time

### LINKED ISSUE #147: Give reenqueue a reasonable "after" interval in the reconcile process

### PR DESCRIPTION
**Pull request by Ghostbaby**
Add reconcile wait requeue time

Fixes #147

Signed-off-by: zhuhuijun <zhuhuijunzhj@gmail.com>

### CODE REVIEW

File: controllers/harborcluster_controller.go [hunk 1]
```diff
@@ -45,12 +47,15 @@ type HarborClusterReconciler struct {
...
-	goharborv1.ComponentDatabase: goharborv1.DatabaseReady,
-}
+var (
+	ComponentToConditionType = map[goharborv1.Component]goharborv1.HarborClusterConditionType{
+		goharborv1.ComponentHarbor:   goharborv1.ServiceReady,
+		goharborv1.ComponentCache:    goharborv1.CacheReady,
+		goharborv1.ComponentStorage:  goharborv1.StorageReady,
+		goharborv1.ComponentDatabase: goharborv1.DatabaseReady,
+	}
+	ReconcileWaitResult = reconcile.Result{RequeueAfter: 30 * time.Second}
```
Comment (steven-zou) [inline controllers/harborcluster_controller.go:57]: Is it reasonable to use a fix 30 sec as the next reconcile time?

Comment (Ghostbaby) [reply controllers/harborcluster_controller.go:57]: yes, only in the case of returning an error, will wait for 30s.
